on: [push]

env:
  PYTHON_VERSION: '3.7'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-bugbear flake8_simplify
    - name: Flake8
      run: |
        flake8 -v
  build:
    needs: [lint]
    if: needs.lint.result == 'success' && contains(github.ref, '/tags/') && startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v3
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry poetry-dynamic-versioning-plugin
    - name: Build
      run: |
        poetry build
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_URL: ${{ github.server_url	}}
        GITHUB_REPO: ${{ github.repository }}
        GITHUB_TAG: ${{ github.ref_name }}      
      run: |
        RELEASE_MESSAGE=$(git tag | tail -2 | paste -sd '*' | sed -r 's/\*/.../')
        RELEASE_MESSAGE="**Full Changelog**: ${GITHUB_URL}/${GITHUB_REPO}/compare/${RELEASE_MESSAGE}"
        echo $GITHUB_TAG >.message
        echo "" >>.message
        echo "${RELEASE_MESSAGE}" >>.message
        hub release create -a $(find dist -name '*.tar.gz') -a $(find dist -name '*.whl') -F .message $GITHUB_TAG
        
        

